export {default as Header} from './header/Header'
export {default as Hero} from './hero/Hero'
export {default as Gear} from './gear/Gear'
export {default as Menu} from './menu/Menu'
export {default as Footer} from './footer/Footer'
export {default as Scrollingtext} from './scrollingtext/Scrollingtext'